### ISSUE TITLE
Upgrade TSLint v5.8

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/tslint-config-fluct#37] opened 2017-10-23 02:48 UTC
https://github.com/palantir/tslint/releases

**Comment by kanufy** [comment] 2017-10-23 08:27
## deprecated rules
- typeof-compare
  - 現状設定されてるので消そう

## new rules
- [no-return-await](https://palantir.github.io/tslint/rules/no-return-await/)
  - よさそう
- [no-redundant-jsdoc](https://palantir.github.io/tslint/rules/no-redundant-jsdoc/)
  - よさそう
- [no-duplicate-switch-case](https://palantir.github.io/tslint/rules/no-duplicate-switch-case/)
  - よさそう
  - eslintにもある ( https://eslint.org/docs/rules/no-duplicate-case )しhttps://github.com/voyagegroup/eslint-config-fluct でも有効にしている
- [no-implicit-dependencies](https://palantir.github.io/tslint/rules/no-implicit-dependencies/)
  - いいかなーとおもうけど、例えばlocales等のTSで書かれていないmodule？などを読み込む際にエラー吐かれるので悩ましいかも
  - このimportは除外するみたいなオプションがなく、devDependenciesやoptionalDependenciesまでを許容するオプションしかないので現状扱いづらそうな気がした
- [no-unnecessary-class](https://palantir.github.io/tslint/rules/no-unnecessary-class/)
  - うーん悩ましい。 `constructor() {}` みたいなのはサクッとつくってるときに結構ありそうかなーとおもうので有効にするなら  `"allow-constructor-only"` いれたいかなあ。
  - eslintには [no-useless-constructor](https://eslint.org/docs/rules/no-useless-constructor) があるがeslint-config-fluctでは無効にしている
- [ban-comma-operator](https://palantir.github.io/tslint/rules/ban-comma-operator/)
  - よさそう

## new rule options
ざっくりみたけどこれがあるから使おうぜみたいなのはないようなきがした

**Comment by saneyuki** [comment] 2017-10-23 10:49
FYI: I opened https://github.com/voyagegroup/tslint-config-fluct/pull/38 (feel free to close it!)

-------------------------

> no-implicit-dependencies
> - いいかなーとおもうけど、例えばlocales等のTSで書かれていないmodule？などを読み込む際にエラー吐かれるので悩ましいかも
> - このimportは除外するみたいなオプションがなく、devDependenciesやoptionalDependenciesまでを許容するオプションしかないので現状扱いづらそうな気がした

We can avoid a such problem by these approach: 

- TypeScript 2.6 has [`// @ts-ignore` comment](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#suppress-errors-in-ts-files-using--ts-ignore-comments) to suppress errors
- Or, we can escape the error with placing dummy `d.ts` file like this:
    - `bar.js`: Webpack, rollup, or other module bundlers see this file on module linking phase of them.
    - `bar.d.ts`: TypeScript compiler see this file on type-checking phase.

So I feel your worry would not prevent to enable this rule.

-------------------------

> no-unnecessary-class

I think this would be valuable to detect a class having only static members as detecting a refactoring chance. In modern JavaScript, we have a module. We should replace a "namespace" class to have only static members with exporting simple functions and variables.

**Comment by nekoya** [comment] 2017-10-24 02:25
@kanufy 

>no-implicit-dependencies
> - いいかなーとおもうけど、例えばlocales等のTSで書かれていないmodule？などを読み込む際にエラー吐かれるので悩ましいかも

We already have `d.ts` file for each JS modules, and I think it is our common rule.

Did you caught such errors on existing projects?

**Comment by nekoya** [comment] 2017-10-24 02:50
We've had a conversation and confirm the errors.

It was not caused by module definition, but because of our webpack setting.

In some cases, we use [resolve.alias](https://webpack.js.org/configuration/resolve/) option to import internal modules by absolute path. The rule `no-implicit-dependencies` recognizes these import sentence as error.

**Comment by nekoya** [comment] 2017-10-24 02:55
I feel this rule is useful to keep robustness of our code, so I'd like to enable it as a default.

**Comment by kanufy** [comment] 2017-10-24 05:10
確認しましたん！
`no-implicit-dependencies` 有効でよさそう

**Closed** 2017-10-24 05:13 UTC
Labels: A-rules
